name: Backend CD

on:
  workflow_run:
    workflows: ["WorkSphere Backend CI"]
    types:
      - completed

permissions:
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: backend-ci.yml
        run_id: ${{ github.event.workflow_run.id }}
        name: WorkSphere-API
        path: ./publish

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure App Service
      uses: azure/webapps-deploy@v3
      with:
        app-name: worksphere-api
        package: ./publish








